FROM gradle:8.12-jdk21 AS build

WORKDIR /home/gradle/project
COPY --chown=gradle:gradle . .
RUN gradle :qa6-gateway:bootJar --no-daemon

FROM eclipse-temurin:21-jre-jammy

RUN mkdir -p /app && chown 99993:99993 /app
WORKDIR /app
COPY --from=build --chown=99993:99993 /home/gradle/project/qa6-gateway/build/libs/qa6-gateway-0.1.0-SNAPSHOT.jar app.jar

USER 99993:99993
EXPOSE 9000
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=70.0", "-XX:+UseSerialGC", "-jar", "/app/app.jar"]
